### ISSUE TITLE
workspace/rpc: object refresh not implemented

### ISSUE THREAD

**Issue by progrium** [manifold/tractor#72]
Object "refreshing" means calling reload on all the object's components (disabling in reverse order, then enabling in forward order -- though i think this is already done in the manifold package). There is a gear next to the object title in the inspector with the menu item to refresh (similar to reload on individual components). However it's not connected up in workspace/rpc so it's not functional.

**Comment by technoweenie** [comment]
Object refresh is hooked up in theia here:

https://github.com/manifold/tractor/blob/ed544ece7a063c4279399e86e9fe2040620094dd/studio/plugins/inspector/media/inspector/inspector.js#L93-L104

With a few prints in `workspace/rpc`, I can confirm the command is run:

https://github.com/manifold/tractor/blob/ed544ece7a063c4279399e86e9fe2040620094dd/pkg/workspace/rpc/handlers.go#L183-L203

I ran into some issues though, with this workflow:

1. create new object
2. Add file explorer component
3. Add `/tmp` path
4. Click `Refresh` on object

I know it hit the server. I'm assuming the watcher is working because reloading the component triggered #79.

Is it possible that the new objects from the `/tmp` files aren't being sent back to the client somehow?

**Comment by progrium** [comment]
Oh, maybe it is implemented? I thought I saw it wasn't.

**Comment by progrium** [comment]
I saw an unused Reload rpc handler and thought that was this. Hah.
